Auto-generate EPS files from scans of drawings ...
Drawings are usually meant to be embedded in the TeX itself
via includegraphics. Hence, if scanning, assume EPS files
required and generate them accordingly

Also, add these to the corresponding vault/ folder.
For now, not git adding them

Do nothing with SVGs generated from LaTeX created PDFs alone (tex-*.svg)

diff --git a/vault/bin/paper2svg b/vault/bin/paper2svg
--- a/vault/bin/paper2svg
+++ b/vault/bin/paper2svg
@@ -5,29 +5,53 @@ let cut_bottom=1
 let cut_left=1
 let cut_right=1
 
-while getopts "l:t:r:b:" option ; do 
+while getopts "l:t:r:b:q:n:k:" option ; do 
   case $option in 
     t) cut_top=$OPTARG ;;
     l) cut_left=$OPTARG ;;
     r) cut_right=$OPTARG ;;
     b) cut_bottom=$OPTARG ;;
+    q) id=$OPTARG
+       type="q" ;;
+    n) id=$OPTARG
+       type="snippets" ;;
+    k) id=$OPTARG
+       type="skills" ;;
     \?) exit 1 ;;
   esac
 done 
 
+if [ -z ${id+x} ] ; then 
+  echo "[Error]: Specify one of -q|-n|-k <integer-id>" 
+  exit 1
+fi 
+
+if [ $type == "q" ] ; then 
+  dir_vault=$(readlink -f $(ls -d $VAULT/$type/*/$id))
+  dir_tmp=$HOME/tmp/q/
+else 
+  dir_vault=$(readlink -f $(ls -d $VAULT/$type/$id))
+  dir_tmp=$HOME/tmp/$type/
+fi 
+
+# Ensure $dir_tmp exists 
+if [ ! -e $dir_tmp ] ;  then mkdir $dir_tmp ; fi 
+
+
 # Get the last argument = TeX filename 
 shift $((OPTIND-1))
-fname=$(basename $1 | cut -d'.' -f1)
-author=$(pdfinfo $1 | grep Creator | sed -e "s/Creator:[[:space:]]*//g")
+src_pdf=$dir_tmp/scan.pdf 
+cp $1 $src_pdf 
+cd $dir_tmp 
 
 # author = TeX if generated by pdflatex OR dvipdf OR ps2pdf 
+author=$(pdfinfo scan.pdf | grep Creator | sed -e "s/Creator:[[:space:]]*//g")
 
 if [[ $author == "TeX" || $author =~ ^dvips ]] ; then 
   # Output: tex-%d.svg 
 
-  echo "TeX" 
-  pdf2svg $1 $fname-%d.svg all 
-  for f in `ls $fname*.svg` ; do 
+  pdf2svg scan.pdf scan-%d.svg all 
+  for f in `ls scan-*.svg` ; do 
     n=$(basename $f | cut -d'.' -f1 | cut -d'-' -f2)
     svgclip.py -o tex-$n.svg $f 
     rm -f $f 
@@ -35,7 +59,12 @@ if [[ $author == "TeX" || $author =~ ^dvips ]] ; then
 else
   # Output: prefab-%d.svg 
 
-  pdftoppm $1 pdf 
+  labels=$(printf "%c" {A..Z})
+  let n_prefab=$(ls $id-*.eps | wc -l)
+
+  pdftoppm scan.pdf pdf 
+
+  echo "Generating ... "
 
   for f in `ls pdf-*.ppm` ; do 
     n=$(basename $f | cut -d'.' -f1 | cut -d'-' -f2)
@@ -61,10 +90,20 @@ else
 
     # Second Pass: Run potrace again to get cropped SVG
     potrace -s --tight --group -r 300 prefab-$n.pgm
+    eps_name=$(echo $id-${labels:$n_prefab:1}.eps)
+
+    echo "... $eps_name"
+    inkscape -E $eps_name prefab-$n.svg  
+    cp $eps_name $dir_vault/
+
+    let n_prefab=n_prefab+1
   done 
 
   # Clean up 
-  rm -f pdf-*.ppm prefab-*.pgm pdf-*.pgm 
+  rm -f pdf-*.ppm prefab-*.{svg,pgm} pdf-*.pgm 
 fi 
+
+# cd back 
+cd - 
 
 
